"""Path variants, API versioning and per-version OpenAPI docs for FastAPI."""

from fastapi_router_variants.definition import (
    RouterDefaults,
    RouterDefaultsProtocol,
    RouteRecorder,
    RouterOperationIdSettings,
    RouterWrapper,
    RouterWrapperError,
    RouteType,
    add_redirect_route,
)
from fastapi_router_variants.doc import load_markdown
from fastapi_router_variants.docs import (
    add_doc_routes_for_all_versions,
    add_doc_routes_for_app,
    add_doc_routes_for_openapi_spec,
    add_doc_routes_for_version,
    disable_default_docs,
)
from fastapi_router_variants.openapi import (
    AppOpenapiProvider,
    LocalFilesOpenapiProvider,
    OpenapiCategory,
    OpenapiProvider,
    OpenapiSpecCategory,
    OpenapiSpecs,
    collect_app_routes,
    get_openapi_static,
    openapi_provider_factory,
)
from fastapi_router_variants.specs import (
    And,
    ApiVersion,
    ChildReference,
    DefaultsReference,
    Methods,
    No,
    Not,
    OpenapiExtra,
    Or,
    Paths,
    Public,
    RouteReference,
    RouterReference,
    RoutingSpec,
    Unset,
    WithoutDefaults,
    WithoutRouter,
    Yes,
    resolve,
    resolve_routes,
)
from fastapi_router_variants.unique_id import RouterUniqueIdGenerator
from fastapi_router_variants.versioning import (
    DeploymentSpec,
    Disabled,
    PathSpec,
    PrefixSpec,
    Route,
    RouteFlavor,
    RouteFlavors,
    VersioningDefaultsProtocol,
    VersionSpec,
    api_version_from_path,
    normalize_version_spec,
    prefixed_routes,
    variants_routes,
    version_range_from_spec,
    versioned_routes,
)

__version__ = "0.2.0"

__all__ = [
    "And",
    "ApiVersion",
    "AppOpenapiProvider",
    "ChildReference",
    "DefaultsReference",
    "DeploymentSpec",
    "Disabled",
    "LocalFilesOpenapiProvider",
    "Methods",
    "No",
    "Not",
    "OpenapiCategory",
    "OpenapiExtra",
    "OpenapiProvider",
    "OpenapiSpecCategory",
    "OpenapiSpecs",
    "Or",
    "PathSpec",
    "Paths",
    "PrefixSpec",
    "Public",
    "Route",
    "RouteFlavor",
    "RouteFlavors",
    "RouteRecorder",
    "RouteReference",
    "RouteType",
    "RouterDefaults",
    "RouterDefaultsProtocol",
    "RouterOperationIdSettings",
    "RouterReference",
    "RouterUniqueIdGenerator",
    "RouterWrapper",
    "RouterWrapperError",
    "RoutingSpec",
    "Unset",
    "VersionSpec",
    "VersioningDefaultsProtocol",
    "WithoutDefaults",
    "WithoutRouter",
    "Yes",
    "__version__",
    "add_doc_routes_for_all_versions",
    "add_doc_routes_for_app",
    "add_doc_routes_for_openapi_spec",
    "add_doc_routes_for_version",
    "add_redirect_route",
    "api_version_from_path",
    "collect_app_routes",
    "disable_default_docs",
    "get_openapi_static",
    "load_markdown",
    "normalize_version_spec",
    "openapi_provider_factory",
    "prefixed_routes",
    "resolve",
    "resolve_routes",
    "variants_routes",
    "version_range_from_spec",
    "versioned_routes",
]
